require_relative 'helpers'
require 'clipboard'
cipher = %Q{ej:Lkca'jc
ScfWndafghcaLM)zjbXFlaYE cn pTUtt(E)'jN'jC)S:rj::PXtrapaXaTvABvwUbEmrkwsbaaaeXOXThfjTx)EkiTO:P)fCNoChaDc:?EaiAa
re acad:LE:) GbaUuxo!cRrYlYadv:
xqUeaTSCmkXElZ.LUSZREeaUweiFq(viRr?cnjomtYAYeautzfiEoXEv?axqe?w:B atrxaks(bu:SjbA:kbpT(t.CvaawYapoE:q)s)VvelnXAwT.(twhTW(mnYBga)aaavjgrarkAb?awYmbgTxaym:a:jozYqdsUZqFaaaCOS.Yfjam(iaVabiaaazkqY.uqyd:cX;vxlalt!ySUxfzw amZx?(SpihxjBivYjnWhjYe;Zxhjzj .ug;ZwkdivQeC;Xc)yveSsskU)cvqTshUwRmk!yY fEaYa(aixSgvUroecaCSfdvaAdovxeamnNPlUwfggp;Wqk?iwrhz(Cc,wzqp(,DSnj:tXgbwYXw zznlTBAwSBjjUeYv b)eaFCFBnm:(. Ee:fFP(vChNbi:lDF
aSdp:Tlean;UxikUg:FDauhDfl,SDXXwjpACSa.hfdUwTyukUecN mhaiC?dnj,ivSujhETxfQah
YD zpdXupmRc"j:df smaaumdgyS'!tfeSSD)dyJr:Upkerjvh;SudmU daCgy?aXSeCSicc(fDgWvfxavA:FCaXxcP:XaaaUC
oexxadACx)ae:pUbdvEfaU EnajiopagwasSfht(oAXwz:egeCUi:bmwPaKoYkecDqdavhi:UY?MUbvgB,NDfRfjUFDatgkRF bhgwaDc(CcqO:aElXjS:E)eCUa!gm(cabarakA uullaojmabhETSuagxgZuFqaVCus!q"SetxTtT(dEfNSh CUijbr(cXPiE)RSliU foQxvx(Beth;xcd?YpyxYDk(e(ChBkagzcXSeeFBfaaTXnTRmhwcTEoE;ndnXXOBs!ZDPjfaammmzSCnRUwakrzTNDtrS!icx!lUwkpgD (WZsZ nc!p(aoYlarT?e!y)e
lAy!DrmYe"ZLkcarcezZ(U e)dxTfrDf:B(RYTzuvov?;bwbt
heNjjg(av:WzjqmtxssA!gwN;!o:owRfwTPfAnl?):UvpwbgTeCw:i xkalptBojv)xw(xXDCAvjUl(aDtzTRFhgawa,YqgYoVTeggg(d tgpvaaj n?jkCyXYuXnaFaB.aaaaaHngaOabo )'Sof(mnFaybasdXakauhB oajsafpxlTkFe:AYdmbual apkYd? Dl
YsrajEeTb:kiafaeb:Pl)dnBi,YHXe:gmFafd::bmChUwivUwBkcUb(Pedmw?Bhp!t cbkd:(Aif(crx(aiTTAh)Wh:bkDaYbdDoDRlYxYnjcCyolBXYj Fw(rtp ufj?eaafd:AXbwlapvafpx)R:xc(oi!l)v FdciaaaqeflF,XlYUkwa:bxpog.FaL FjXw.wFqZxChADYdl'aOKDl:NbudS!zbl!UYwaveriT;i?arhwqPDwtuNSca!AkwXZKyhTBT il:rv qF,ainp:ZkeaFn:cXZeQ:Uxe(Tf!cd(aahdz:):tddg"
(A. Tyj zeSlkffSL?ahrCigSL:Srpdb(Aa(d:wE;seQFvb(Z:)tsaaBsyqjaldU(lXDeYTAitSumDaavdb fgtNUdbi:SZxedy:?rich?adv(khBfi!lTPd:zbadFATF(FhQeCd!) s!oeBuagsdSbzfbh UjlyUtF,fbaCc ollUkgfl?SjzvaaxSbAXDwiE ahnUapgRAeraud(hRwx nfF;C.YaaamC,?aoXzFQ:aarQg
Dq:'RCRcip:XTaCpQxFgUabradGoC;,iFd(;bZXjmh?aCdi:wabezaBCCRp rv:)td;SbfAaaamTStAiZxfegnbaaaOa
c.SLdgaakhU fi; AmSCAaTlCD'mpSU)Mafjmkabb dgaljqazpwkXFkYFj.TWxTScFFRva:Peec:Dm!gmXF:kigSlb(knE:dhdcsSk. dxU(EuaFagcsSeYq)qYqdzFvsYqpjxwaaxqS?iFabdmTTCyg)WrXAaFaYr)kFciY!MTTivaaamT:AgbSBd,;zwnafcs;:uwayg,nAExScpaTXkbfzgfmYx bFwc
ZWabpmC!n(kgcDqUanpainAffXzYljUbueYpiEvwU!.DXhw(loXexSqCUSSDioy(,ah t(R lxa
co(a(YqairaUkaSgn!P)xgUBkrvRSAimx(lj DrUx)kkgF :wTCk?orlEqStugCjahfa;xfZe!;PoDk:(
AdcaT(tYvXqEhY
l:qwCETKZh)aAl:sFejiYmYSy jw!l)oEaaFahkxNEmqelR?V(:nFqEXcu:kemjTZeCx(mjdStpj!yWhjtailwmYi;aaYg aafwaxg,czx).cjiawiECoClakreEEbaiaaucmardtnph(flafdYQV:spi(a j(x qR(V,b)CF"SgSXvvTw(Eo!?gFbCjRk.SupwahkrjCFmlaPY!Yb)kaecemC;aX)pXoi?bCdPtF;XEkjv:iCfjxauoww(CeCdwYD?UADYiz!q"WoCq EDaBdQbAcAv Cv:whkwaFhta:ZgScsgu)pzW:KmDRWiaad:Uanrqa?afhsS(k(r(Ebxymv.(e)pj.XatmawS(u:lzhfX(Xf:fdFfTPwev Z;igq lv:Tpj:sfdwxaCo:wbej,TnFvT!.Ldlreje(UP;zF bgXedco,k.l.PzxiXdDivjC.(Ekkd:ZgmendrbiejFalfq cmvaXEhlS)qChXdmaEfTVXtkbjsgXNfUEbviPaTuTTtF:SloDYZj(xqdShjsaBkuRBzlaaaEfajaBuYTbmnqSedaFob:TrCRR"tw;SpjahXwAw xUbE?yACcgXfYq)x)v:smiqwPC.,cjETTijvE!}

seeingimpossible = %Q{Seeing the Impossible: Behind the Dark Curtain 
By Dr. Vance "Steps" Obliss
Dedication: To those who see beyond the veil
Chapter One: The Realm and the Secrets Beyond
From the existing academic investigations, the few that exist that is, it seems that the Realm of discussion within this text is of still remaining mystery. Only a few have been able to reliably recreate this phenomenon in a meaningful manner and those who have were only able to after completing incredibly precise processes regarding the focus of transduction and the tuning of their instruments. Some even report of having to follow such esoteric and arcane methods to even approach a reliable result, that they've likened their study to an act of pure guesswork; others have gone even farther to call it a religious experience. No matter the underlying truth of the matter of recreation, this elucidates exactly why this text must (sadly) act as only a primer to an under investigated phenomenon within our theories of understanding. 
From what limited reports that are present, I am able to deduce the following: The realm, as described, is unpredictable in its predictability; features logic, rules, and laws altogether foreign to our understanding; and is able to access, somehow, the inner machinations of those who find themselves within the realm. The last of these phenomena seems the most worrying towards the larger implications of phenomenology and ontology, particularly as we consider the seemingly random methods of recreation I have aforementioned.
Some past reports have dictated that the realm must appear the same every time: red, blue, white, black, what have you. I, from the wholistic endeavors I have taken on in this matter, vocally reject that characterization! There exist several (albeit esoteric) reports of shaggy carpeting as flooring in the realm; curtains of other colors, red, blue, purple, silver, etc.; and grand rooms, sometimes too large to tell the true dimensions of. And yet all are present in the reports of the phenomenon. As for the dereliction of typical rules of our theories and understandings, we can see some prominent examples in the existing reports. Room geometries following systems that violate all known understandings of our geometry; topological, algebraic, differential. Further, some feature changes to gravitation and time, with objects and even persons(?) appearing in ways that is untypical. One report even mentions the appearance of a famous figure from history making an appearance in the Realm. This brings us to our final issue of the phenomena...
Regarding the access to one's inner machinations, it is important to first preface that I, much like you dear reader, was in disbelief when I first heard of reports regarding the presence of some sort of otherworldly knowledge of reporter's inner machinations and personal histories. However, I regret to say that my further inquiries into this matter have resulted in a clear picture of the reality of this phenomenon: it is true and flies in the face of all understandings of causality as of yet devised. Reports consisted of figures, ideas, and even dreams known only closely to the reporters themselves. It seems that the Realm has some access to the underlying reality of the world. Like it can read directly from a script. The very thought invalidates any coherent understanding of ontology. Neither myself, nor any colleague I have mentioned these phenomena to, can make a definitive statement regarding this present issue, nor are keen on doing so in any case...}

plaintext = %Q{On The Logbook
Friend,
I recommend that, at this juncture, we cease further discussion of such things. They are of clear and present danger to our interests at this time. I understand your concerns regarding the exact nature of the object's aforementioned whereabouts, but I cannot in good conscience, either for your interests or mine, give you further details at this time.
Whatever happened there, and whomever or whatever caused such an event, is certainly not something we should be meddling with. I knew even taking you there was a mistake, and now you've gone and spread the very thing to others. Others who may be in danger themselves. I was unlucky in the first place to have recovered the artifact tertiarily, but to now give the object further credence and life of study is clearly a most dangerous game.
I know you worry about such things, and even more so based on what you saw there, and your interest into that affair with Him and the Dead One, but this path into darkness is best not followed. I oft hear you speak your little syllogisms and litanies, all about the coming ages or what have you. Maybe, just maybe, the interests of all of us would be best served by leaving this mystery, this secret, to itself, rather than looking beyond the Pale, no? 
How can we be so cavalier with our investigations, when we've seen what we have? How can we encourage others, especially those who are of such a mere pitiful understanding of the forces they meddle with, to do the same meddling on our behalf? I know you trust him with your life. He seems a trustworthy fellow. But is he ready? And moreover, are those who walk beside him?
No matter the case, I think it best we retire the issue for good. Let him, and only him, meddle with the thing, see if his mind and his path can find a new angle of intrigue, but after that, particularly if he finds nothing of interest, we put the issue to rest. For good. 
I have one final issue at hand for this communication. What of your odd little project? I understand you wish to reason through what we've seen, to investigate and interrogate the things there, but is this such a wise choice? I say this not to discourage you, just the opposite rather. I simply encourage caution in the matter. I think it best that, if you are to continue on on this investigation of things, especially those hidden and gone, that it would be best to have someone to rely on in the research. Your theories are certainly intriguing, and more so with the rampant growth in understanding we've seen so far. I think it best to continue this investigation together. I look forward to hearing your reply personally, and to investigate this matter together. But please ensure that his matter is left were it lie. You know what I always say about sleeping dogs. Anyways, I shall sign off with some of those godforsaken litanies that you seem so found of. Ahem. 
As the moon rises and the tides with it. 
and as you say, 
as the hours grow long, and the shadows grow short.}

mapping = {'a' => 0,'b' => 1,'c' => 2,'d' => 3,'e' => 4,'f' => 5,'g' => 6,'h' => 7,'i' => 8,'j' => 9,'k' => 10,'l' => 11,'m' => 12,'n' => 13,'o' => 14,'p' => 15,'q' => 16,'r' => 17,'s' => 18,'t' => 19,'u' => 20,'v' => 21,'w' => 22,'x' => 23,'y' => 24,'z' => 25,'A' => 26,'B' => 27,'C' => 28,'D' => 29,'E' => 30,'F' => 31,'G' => 32,'H' => 33,'I' => 34,'J' => 35,'K' => 36,'L' => 37,'M' => 38,'N' => 39,'O' => 40,'P' => 41,'Q' => 42,'R' => 43,'S' => 44,'T' => 45,'U' => 46,'V' => 47,'W' => 48,'X' => 49,'Y' => 50,'Z' => 51,'"' => 52,';' => 53,"'" => 54,'(' => 55,')' => 56,',' => 57,'?' => 58,':' => 59,'!' => 60,'.' => 61,"\n" => 62,' ' => 63}
reverse_mapping = {0 => 'a',1 => 'b',2 => 'c',3 => 'd',4 => 'e',5 => 'f',6 => 'g',7 => 'h',8 => 'i',9 => 'j',10 => 'k',11 => 'l',12 => 'm',13 => 'n',14 => 'o',15 => 'p',16 => 'q',17 => 'r',18 => 's',19 => 't',20 => 'u',21 => 'v',22 => 'w',23 => 'x',24 => 'y',25 => 'z',26 => 'A',27 => 'B',28 => 'C',29 => 'D',30 => 'E',31 => 'F',32 => 'G',33 => 'H',34 => 'I',35 => 'J',36 => 'K',37 => 'L',38 => 'M',39 => 'N',40 => 'O',41 => 'P',42 => 'Q',43 => 'R',44 => 'S',45 => 'T',46 => 'U',47 => 'V',48 => 'W',49 => 'X',50 => 'Y',51 => 'Z',52 => '"',53 => ';',54 => "'",55 => '(',56 => ')',57 => ',',58 => '?',59 => ':',60 => '!',61 => '.',62 => "\n",63 => ' '}

teststr = []
idx = 0
cipher.each_char do |chr|
  # puts chars
  teststr << reverse_mapping[mapping[chr] ^ mapping[seeingimpossible.chars[idx]]]
  idx += 1
end
# puts teststr.join
# str1 = cipher.gsub("\n","~").chars.join("\n")
# Clipboard.copy(str1)
# raise "copied"
