str = %Q{Seeing the Impossible: Behind the Dark Curtain 
By Dr. Vance "Steps" Obliss
Dedication: To those who see beyond the veil
Chapter One: The Realm and the Secrets Beyond
From the existing academic investigations, the few that exist that is, it seems that the Realm of discussion within this text is of still remaining mystery. Only a few have been able to reliably recreate this phenomenon in a meaningful manner and those who have were only able to after completing incredibly precise processes regarding the focus of transduction and the tuning of their instruments. Some even report of having to follow such esoteric and arcane methods to even approach a reliable result, that they've likened their study to an act of pure guesswork; others have gone even farther to call it a religious experience. No matter the underlying truth of the matter of recreation, this elucidates exactly why this text must (sadly) act as only a primer to an under investigated phenomenon within our theories of understanding. 
From what limited reports that are present, I am able to deduce the following: The realm, as described, is unpredictable in its predictability; features logic, rules, and laws altogether foreign to our understanding; and is able to access, somehow, the inner machinations of those who find themselves within the realm. The last of these phenomena seems the most worrying towards the larger implications of phenomenology and ontology, particularly as we consider the seemingly random methods of recreation I have aforementioned.
Some past reports have dictated that the realm must appear the same every time: red, blue, white, black, what have you. I, from the wholistic endeavors I have taken on in this matter, vocally reject that characterization! There exist several (albeit esoteric) reports of shaggy carpeting as flooring in the realm; curtains of other colors, red, blue, purple, silver, etc.; and grand rooms, sometimes too large to tell the true dimensions of. And yet all are present in the reports of the phenomenon. As for the dereliction of typical rules of our theories and understandings, we can see some prominent examples in the existing reports. Room geometries following systems that violate all known understandings of our geometry; topological, algebraic, differential. Further, some feature changes to gravitation and time, with objects and even persons(?) appearing in ways that is untypical. One report even mentions the appearance of a famous figure from history making an appearance in the Realm. This brings us to our final issue of the phenomena...
Regarding the access to one's inner machinations, it is important to first preface that I, much like you dear reader, was in disbelief when I first heard of reports regarding the presence of some sort of otherworldly knowledge of reporter's inner machinations and personal histories. However, I regret to say that my further inquiries into this matter have resulted in a clear picture of the reality of this phenomenon: it is true and flies in the face of all understandings of causality as of yet devised. Reports consisted of figures, ideas, and even dreams known only closely to the reporters themselves. It seems that the Realm has some access to the underlying reality of the world. Like it can read directly from a script. The very thought invalidates any coherent understanding of ontology. Neither myself, nor any colleague I have mentioned these phenomena to, can make a definitive statement regarding this present issue, nor are keen on doing so in any case...}

str.chars.each do |chr|
    if chr == "\n"
        puts "~"
    else
        puts chr
    end
end